name: gee
description: Gönüllü Eşit Eğitim
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  cupertino_icons: ^1.0.2
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/pictures/icon.png
    - assets/pictures/user.png
    - assets/pictures/campus.png
    - assets/pictures/question.png
    - assets/pictures/user_background.jpg
    - assets/pictures/non_photo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: ./assets/fonts/Montserrat-Bold.ttf
        - asset: ./assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
        - asset: ./assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: ./assets/fonts/Montserrat-Light.ttf
        - asset: ./assets/fonts/Montserrat-LightItalic.ttf
          style: italic
        - asset: ./assets/fonts/Montserrat-Regular.ttf
        - asset: ./assets/fonts/Montserrat-Thin.ttf
        - asset: ./assets/fonts/Montserrat-ThinItalic.ttf
          style: italic